#!/bin/bash
# Regenerate gleanin/SKILL.md from glean/artifacts/*.md
#
# Usage:
#   bash ~/.claude/skills/gleanin/sync.sh
#
# Reads artifacts from GLEAN_DIR/artifacts/ (default: ~/glean/artifacts/)
# and rewrites the Rules section in this skill's SKILL.md.
# Each artifact section renders rule (≤5 lines) + check (≤1 line).
set -u

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GLEAN_DIR="${GLEAN_DIR:-$HOME/glean}"
ARTIFACTS_DIR="$GLEAN_DIR/artifacts"
SKILL_FILE="$SKILL_DIR/SKILL.md"

if [ ! -d "$ARTIFACTS_DIR" ]; then
  echo "No artifacts dir at $ARTIFACTS_DIR. Nothing to sync."
  exit 0
fi

python3 -c "
import sys, os, glob

artifacts_dir = os.path.expanduser('$ARTIFACTS_DIR')
skill_file = os.path.expanduser('$SKILL_FILE')

rules = []
for f in sorted(glob.glob(os.path.join(artifacts_dir, '*.md'))):
    name = os.path.splitext(os.path.basename(f))[0].replace('-', ' ').title()
    with open(f) as fh:
        content = fh.read()

    lines = content.split('\n')
    in_frontmatter = False
    collecting = False
    what = []
    rule = []
    check = []
    current = None

    for line in lines:
        s = line.strip()
        if s == '---':
            if not collecting:
                in_frontmatter = not in_frontmatter
            continue
        if in_frontmatter:
            continue
        if s.startswith('# ') and not collecting:
            continue

        if s.startswith('**What went wrong:**'):
            collecting = True
            current = 'what'
            what.append(s.split(':**', 1)[1].strip() if ':**' in s else '')
            continue
        if s.startswith('**Rule:**'):
            current = 'rule'
            rest = s.split(':**', 1)[1].strip() if ':**' in s else ''
            if rest:
                rule.append(rest)
            continue
        if s.startswith('**Check:**'):
            current = 'check'
            rest = s.split(':**', 1)[1].strip() if ':**' in s else ''
            if rest:
                check.append(rest)
            continue

        if not collecting:
            continue

        # Stop at unknown bold header
        if s.startswith('**') and ':**' in s:
            break

        if current == 'what':
            what.append(s)
        elif current == 'rule':
            rule.append(s)
        elif current == 'check':
            check.append(s)

    rule_text = '\\n'.join(r for r in rule if r.strip())[:600]
    check_text = ' '.join(c for c in check if c).strip()[:200]

    rules_text = f'**Rule:**\\n{rule_text}\\n\\n**Check:** {check_text}'
    rules.append((name, rules_text))

# Read existing SKILL.md
with open(skill_file) as f:
    original = f.read()

start_marker = '<!-- Rules are auto-generated'
end_marker = '<!-- end gleanin rules -->'

# Build new rules block
new_rules = '<!-- Rules are auto-generated by sync.sh. Do not edit manually. -->\\n'
for name, text in rules:
    new_rules += f'\\n### {name}\\n\\n{text}\\n'
new_rules += '\\n<!-- end gleanin rules -->'

# Replace
if start_marker in original and end_marker in original:
    before = original.split(start_marker)[0]
    after = original.split(end_marker, 1)[1]
    new_content = before + new_rules + after
else:
    # Append after ## Rules
    header, _, footer = original.partition('## Rules')
    new_content = header + '## Rules\\n\\n' + new_rules + '\\n' + footer

with open(skill_file, 'w') as f:
    f.write(new_content)

count = len(rules)
print(f'gleanin: synced {count} artifacts into SKILL.md')
"
